version: '3'
services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "9093:80"

# 未指定前：默认的网络： composese_1_defalut
networks:
  default:
    external:
      name: compose_2_front
